version: '3.8'

services:
  auth-service:
    build: .
    container_name: auth-service
    restart: always
    ports:
      - "5040:5040"
    volumes:
      - .:/app
    networks:
      - rede-compartilhada

networks:
  rede-compartilhada:
    driver: bridge
